path:
    train_path: datasets/klue-sts-v1.1_train.json
    dev_path: datasets/klue-sts-v1.1_dev.json
    test_path: datasets/klue-sts-v1.1_dev.json

data:
    shuffle: True
    augmentation: False
    max_length : 128

model:
  model_name: 'monologg/koelectra-base-v3-discriminator'
  saved_name: 'base_model'

train:
  seed: 42
  batch_size: 32
  max_epoch: 4
  learning_rate: 5e-5
  logging_step: 100
  drop_out: 0.1
  warmup_ratio: 0.1
  weight_decay: 0.01
  
runner:
  options:
    num_workers: 8